### PR TITLE
Adjusts admin output to keep hrefs

### PR DESCRIPTION
**Pull request by ecaron**
Suggesting this change to keep the translations functional without causing the <a to become &lt;a

### CODE REVIEW

**Comment by ecaron** [comment]
@mbanusic I don't have a copy of Poedit Pro (yet), but I'll get one soon to include the .pot files.
What do you think of this approach for keeping the HTML functional in the admin section? I've been [reviewing some popular options](https://wordpress.stackexchange.com/questions/165357/how-to-make-a-text-with-hyperlink-translatable-in-wordpress), but none of those pass code linting.

I think avoiding HTML whenever possible in translations makes this problem go away, so I removed it from the WordPress Debug link. The Bsky App password link seems important, though, so that'll require a second translation.

**Comment by mbanusic** [comment]
Don't worry, I do, so I can always add to the .pot

For HTML there is option to printf with 

```
printf(
			/* translators: 1: Site name, 2: WordPress */
			__( '%1$s is proudly powered by %2$s' ),
			get_bloginfo( 'name' ),
			'<a href="https://wordpress.org/">WordPress</a>'
		);
		?>
```

**Comment by ecaron** [comment]
When I do that method, the linter posts this complaint:
```
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 72 | ERROR | All output should be run through an escaping function (see the
    |       | Security sections in the WordPress Developer Handbooks), found
    |       | '__'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
--------------------------------------------------------------------------------
```
I haven't found a way to replace the `__` with a different translation method that doesn't render the HTML as text.
Would you want a `phpcs:ignore` on that line, or should we find a different way?

**Comment by mbanusic** [comment]
esc_html_e doesn't work? I used in a couple of places

**Comment by ecaron** [comment]
> esc_html_e doesn't work? I used in a couple of places

`esc_html_e` eventually calls [_wp_specialchars](https://developer.wordpress.org/reference/functions/_wp_specialchars/), and that specifically encodes &, <, >, ", and '. [This post phrases the difference well](https://wordpress.stackexchange.com/questions/31118/should-html-output-be-passed-through-esc-html-and-wp-kses):

> The kses functions should be used when you want to allow some subset of html to be in the result. For example, comments allow some HTML in them for bold, italic, links, and such.
> The esc_html function should be used to escape html completely. No HTML will go through it without being converted to something that will be interpreted as non-HTML by a browser.

**Comment by mbanusic** [comment]
OK, I just tried this:
```
<?php
echo wp_kses(
	__( 'Enter app password. If using BlueSky visit: <a href="https://bsky.app/settings/app-passwords" target="_blank">App passwords</a>', 'neznam-atproto-share' ),
	array(
		'a' => array(
			'href'   => array(),
			'target' => array(),
		),
	)
);
?>
```

and linter is not complaining

**Comment by ecaron** [comment]
@mbanusic Nice solve! I'll ditch this PR.

**Pull request closed without merging**
